from goofish_insight.category_compat import (
    CategoryScopeProfile,
    CATEGORY_SCOPE_PROFILES,
    NON_ANALYTICS_SCOPE_CODES,
    normalize_scope_key,
    resolve_category_code,
    is_analytics_scope,
    non_analytics_scope_codes,
    get_category_scope_profile,
    compatible_scope_keys,
    preferred_legacy_business_domain,
    display_label_for_scope,
    token_aliases_for_scope,
    is_garmin_watch_scope,
    is_apple_computer_scope,
    category_compat_retirement_summary,
)

__all__ = [
    "CategoryScopeProfile",
    "CATEGORY_SCOPE_PROFILES",
    "NON_ANALYTICS_SCOPE_CODES",
    "normalize_scope_key",
    "resolve_category_code",
    "is_analytics_scope",
    "non_analytics_scope_codes",
    "get_category_scope_profile",
    "compatible_scope_keys",
    "preferred_legacy_business_domain",
    "display_label_for_scope",
    "token_aliases_for_scope",
    "is_garmin_watch_scope",
    "is_apple_computer_scope",
    "category_compat_retirement_summary",
]
